# -*- coding: utf-8 -*-
"""Soil_Image_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gneZeGh4jJtZeVhnaVQhFmujy-0XWsut
"""

from google.colab import drive
drive.mount('/content/drive')

dataset_path = "/content/drive/MyDrive/Soil_image_dataset"

import os

for folder in os.listdir(dataset_path):
    print(folder)

import matplotlib.pyplot as plt
import os

folders = os.listdir(dataset_path)

counts = []

for folder in folders:

    folder_path = os.path.join(dataset_path, folder)

    counts.append(len(os.listdir(folder_path)))

plt.figure(figsize=(8,5))

plt.bar(folders, counts)

plt.title("Number of Images per Soil Type")

plt.xlabel("Soil Type")

plt.ylabel("Number of Images")

plt.xticks(rotation=45)

plt.show()

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

img_size = (224,224)
batch_size = 32

datagen = ImageDataGenerator(

    rescale=1./255,

    validation_split=0.2,

    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)

train_data = datagen.flow_from_directory(

    dataset_path,

    target_size=img_size,

    batch_size=batch_size,

    class_mode='categorical',

    subset='training'
)

val_data = datagen.flow_from_directory(

    dataset_path,

    target_size=img_size,

    batch_size=batch_size,

    class_mode='categorical',

    subset='validation'
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.layers import Flatten, Dense, Dropout

cnn = Sequential()

# First Convolution Layer
cnn.add(Conv2D(
    32,
    (3,3),
    activation='relu',
    input_shape=(224,224,3)
))

cnn.add(MaxPooling2D(2,2))

# Second Layer
cnn.add(Conv2D(64,(3,3),activation='relu'))
cnn.add(MaxPooling2D(2,2))

# Third Layer
cnn.add(Conv2D(128,(3,3),activation='relu'))
cnn.add(MaxPooling2D(2,2))

# Flatten Layer
cnn.add(Flatten())

# Dense Layers
cnn.add(Dense(128,activation='relu'))

cnn.add(Dropout(0.5))

# Output Layer (5 classes)
cnn.add(Dense(5,activation='softmax'))

cnn.compile(

    optimizer='adam',

    loss='categorical_crossentropy',

    metrics=['accuracy']
)

cnn.summary()

history_cnn = cnn.fit(

    train_data,

    validation_data=val_data,

    epochs=15
)

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.plot(history_cnn.history['accuracy'])
plt.plot(history_cnn.history['val_accuracy'])

plt.title("CNN Model Accuracy")

plt.xlabel("Epochs")

plt.ylabel("Accuracy")

plt.legend(['Train','Validation'])

plt.show()

cnn.save(
    "/content/drive/MyDrive/soil_cnn_model.h5"
)

print("CNN model saved successfully!")

import numpy as np
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Get predictions
Y_pred = cnn.predict(val_data)

y_pred = np.argmax(Y_pred, axis=1)

# True labels
y_true = val_data.classes

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(8,6))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.title("CNN Confusion Matrix")

plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

from tensorflow.keras.preprocessing import image
import numpy as np

# Class names
class_names = list(train_data.class_indices.keys())

def predict_image(img_path):

    img = image.load_img(
        img_path,
        target_size=(224,224)
    )

    img_array = image.img_to_array(img)

    img_array = np.expand_dims(img_array, axis=0)

    img_array = img_array/255

    prediction = cnn.predict(img_array)

    predicted_class = class_names[np.argmax(prediction)]

    return predicted_class

predict_image(
"/content/drive/MyDrive/soil.jpeg"
)

from tensorflow.keras.applications import VGG16
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten

base_model = VGG16(

    weights='imagenet',

    include_top=False,

    input_shape=(224,224,3)

)

# Freeze layers
for layer in base_model.layers:
    layer.trainable = False